export const SHEET_TABS = {
  Medicines: 'Medicines',
  Medicine_Batches: 'Medicine_Batches',
  Customers: 'Customers',
  Suppliers: 'Suppliers',
  Sales: 'Sales',
  Sale_Items: 'Sale_Items',
  Purchases: 'Purchases',
  Purchase_Items: 'Purchase_Items',
  Expenses: 'Expenses',
  Payments: 'Payments',
  Sales_Returns: 'Sales_Returns',
  Purchase_Returns: 'Purchase_Returns',
  Categories: 'Categories',
  Manufacturers: 'Manufacturers',
  Users: 'Users',
  Settings: 'Settings',
  Activity_Log: 'Activity_Log',
} as const;

export const TAB_HEADERS: Record<keyof typeof SHEET_TABS, string[]> = {
  Medicines: [
    'Medicine ID',
    'Barcode',
    'Medicine Name',
    'Generic Name',
    'Brand Name',
    'Manufacturer',
    'Category',
    'Medicine Type',
    'Strength',
    'Dosage Form',
    'Pack Size',
    'Purchase Price',
    'Selling Price',
    'Retail Price',
    'Current Stock',
    'Minimum Stock Level',
    'Batch Number',
    'Manufacturing Date',
    'Expiry Date',
    'Supplier',
    'Rack / Shelf Location',
    'Prescription Required',
    'Status',
    'Created Date',
    'Updated Date',
  ],
  Medicine_Batches: [
    'Batch ID',
    'Medicine ID',
    'Medicine Name',
    'Batch Number',
    'Supplier',
    'Purchase Date',
    'Manufacturing Date',
    'Expiry Date',
    'Purchase Price',
    'Selling Price',
    'Quantity Purchased',
    'Quantity Remaining',
    'Status',
  ],
  Customers: [
    'Customer ID',
    'Customer Name',
    'Phone',
    'Email',
    'Address',
    'Date of Birth',
    'Gender',
    'Customer Type',
    'Total Purchases',
    'Total Paid',
    'Outstanding Balance',
    'Notes',
    'Created Date',
  ],
  Suppliers: [
    'Supplier ID',
    'Company Name',
    'Contact Person',
    'Phone',
    'Email',
    'Address',
    'NTN / Tax Number',
    'Total Purchases',
    'Total Paid',
    'Outstanding Balance',
    'Notes',
    'Created Date',
  ],
  Sales: [
    'Sale ID',
    'Invoice Number',
    'Customer ID',
    'Customer Name',
    'Sale Date',
    'Subtotal',
    'Discount',
    'Tax',
    'Grand Total',
    'Amount Paid',
    'Remaining Balance',
    'Payment Method',
    'Payment Status',
    'Total Profit',
    'Created By',
    'Notes',
    'Status',
  ],
  Sale_Items: [
    'Sale Item ID',
    'Sale ID',
    'Invoice Number',
    'Medicine ID',
    'Medicine Name',
    'Batch ID',
    'Batch Number',
    'Quantity',
    'Unit Price',
    'Purchase Price',
    'Discount',
    'Tax',
    'Subtotal',
    'Profit',
  ],
  Purchases: [
    'Purchase ID',
    'Purchase Invoice Number',
    'Supplier ID',
    'Supplier Name',
    'Purchase Date',
    'Total Amount',
    'Amount Paid',
    'Remaining Balance',
    'Payment Status',
    'Notes',
    'Created By',
    'Status',
  ],
  Purchase_Items: [
    'Purchase Item ID',
    'Purchase ID',
    'Purchase Invoice Number',
    'Medicine ID',
    'Medicine Name',
    'Batch Number',
    'Manufacturing Date',
    'Expiry Date',
    'Quantity',
    'Purchase Price',
    'Selling Price',
    'Total',
  ],
  Expenses: [
    'Expense ID',
    'Date',
    'Category',
    'Description',
    'Amount',
    'Payment Method',
    'Reference',
    'Notes',
    'Created By',
  ],
  Payments: [
    'Payment ID',
    'Date',
    'Payment Type',
    'Party ID',
    'Party Name',
    'Amount',
    'Payment Method',
    'Reference Number',
    'Related Invoice',
    'Notes',
    'Created By',
  ],
  Sales_Returns: [
    'Return ID',
    'Date',
    'Sale ID',
    'Invoice Number',
    'Customer Name',
    'Medicine ID',
    'Medicine Name',
    'Batch ID',
    'Batch Number',
    'Quantity Returned',
    'Refund Amount',
    'Reason',
    'Restocked',
    'Processed By',
  ],
  Purchase_Returns: [
    'Return ID',
    'Date',
    'Purchase ID',
    'Purchase Invoice Number',
    'Supplier ID',
    'Supplier Name',
    'Medicine ID',
    'Medicine Name',
    'Batch ID',
    'Batch Number',
    'Quantity Returned',
    'Return Value',
    'Reason',
    'Processed By',
  ],
  Categories: ['Category ID', 'Category Name', 'Description', 'Medicine Count'],
  Manufacturers: ['Manufacturer ID', 'Manufacturer Name', 'Country', 'Contact', 'Medicine Count'],
  Users: ['User ID', 'Name', 'Email', 'Role', 'Status', 'Phone', 'Created Date'],
  Settings: [
    'Setting ID',
    'Pharmacy Name',
    'Logo',
    'Phone',
    'Email',
    'Address',
    'Tax Number',
    'Currency',
    'Invoice Prefix',
    'Low Stock Threshold',
    'Expiry Warning Days',
    'Receipt Footer',
    'Default Tax',
  ],
  Activity_Log: ['Log ID', 'User', 'Action', 'Record Type', 'Record ID', 'Date and Time', 'Description'],
};
